alertmanager:
  enabled: false
kubeEtcd: { enabled: false }
kubeControllerManager: { enabled: false }
kubeScheduler: { enabled: false }
kubeProxy: { enabled: false }
prometheus:
  prometheusSpec:
    retention: 3d
    serviceMonitorSelectorNilUsesHelmValues: false
    resources:
      requests: { cpu: 100m, memory: 400Mi }
      limits: { memory: 700Mi }
grafana:
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  resources:
    requests: { cpu: 50m, memory: 100Mi }
    limits: { memory: 250Mi }
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.43.205.216.159.nip.io
