apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshort
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: urlshort
  template:
    metadata:
      labels:
        app: urlshort
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: urlshort
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits:   { cpu: 250m, memory: 128Mi }
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: urlshort-data
